# Generated by Django 3.2.16 on 2024-07-25 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth.user', verbose_name='Подпиcки'),
            preserve_default=False,
        ),
    ]
